name: CICD Using GitHub Action
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Using NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install & build
        run: |
          npm install
          npm run build

        env:
          CI: true
 
  dockerPublish: #creating docker image & pushing into docker hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:          
          push: true
          tags: prodocker21/cicd-test1

  cleanDocker: #stopping and deleting existing/ running containers
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: SSH deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |               
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker rmi prodocker21/cicd-test1

  deployDocker: #running the local build docker image on host 
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: SSH deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST_SSH_PORT }}
          script: |      
              mkdir /home/ubuntu/cicd        
              cd /home/ubuntu/cicd
              docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
              docker pull prodocker21/cicd-test1
              docker run -d -p 80:3000 prodocker21/cicd-test1